### ISSUE TITLE
请教Lua插件开发的问题

### ISSUE THREAD

**Issue by Renkai** [nopdan/docs#1]
作者你好!
最近看了你的文章[脚本开发指南](https://docs.nopdan.com/rime/Scripting.html), 尝试搞点小插件来辅助中英混合输入插件代码在[这儿](https://github.com/Renkai/tiger-code/blob/main/lua/wrap_spaces.lua)目前它大体能按照预期工作,但是有点小问题:
- 我期望使用大小写混合, 比如 `'macOS`, 但是大写字母不被 lua function 捕获, 结果成了 `mac OS`
- 期望使用连字符 `-`, 也不被 fucntion 捕获, 应该是被当翻页键处理了
- 期望在英文后面打标点, 然后在标点后面出空格, 目前版本也实现不了
	
目前做过的尝试:
- 调整 [processers 和 segmentors 的位置](https://github.com/Renkai/tiger-code/blob/main/tigress.schema.yaml#L76) 比如把 speller 和 matcher 放最前面, 没有起意想中的作用.

文档很好, 希望做大做强, 多谢!

**Comment by nopdan** [comment]
你好，这里的文档大多都是搬运的，原文在这里 https://github.com/hchunhui/librime-lua/wiki/Scripting
有任何问题应当在原始[仓库](https://github.com/hchunhui/librime-lua)提交 issue
